# Generated by Django 5.2.16 on 2026-07-21 16:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('idempotency_key', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('reference_number', models.CharField(max_length=64, unique=True)),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('WITHDRAW', 'Withdraw'), ('TRANSFER', 'Transfer')], max_length=16)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('failure_reason', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('from_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_transactions', to='wallets.wallet')),
                ('to_wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_transactions', to='wallets.wallet')),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.CreateModel(
            name='TransactionLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('balance_after', models.DecimalField(decimal_places=8, max_digits=20)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='transactions.transaction')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='wallets.wallet')),
            ],
            options={
                'db_table': 'transaction_ledger',
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status'], name='transaction_status_505a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type'], name='transaction_transac_ddda52_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['completed_at'], name='transaction_complet_6d39d4_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['created_by', 'created_at'], name='transaction_created_f8026f_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='transaction_amount_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('from_wallet__isnull', True), ('transaction_type', 'DEPOSIT')), models.Q(('to_wallet__isnull', True), ('transaction_type', 'WITHDRAW')), ('transaction_type', 'TRANSFER'), _connector='OR'), name='transaction_wallet_consistency'),
        ),
        migrations.AddIndex(
            model_name='transactionledger',
            index=models.Index(fields=['transaction'], name='transaction_transac_58fa36_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionledger',
            index=models.Index(fields=['wallet', 'created_at'], name='transaction_wallet__e05ae3_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionledger',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='ledger_amount_gt_zero'),
        ),
    ]
